const canvas = document.querySelector("canvas");
canvas.width = window.innerWidth;
canvas.height = window.innerHeight;
const context : Context = canvas.getContext("2d");
context.fillStyle = "red";
context.fillRect(0, 0, canvas.width, canvas.height);
context.fillStyle = "white";
context.textBaseline = "top";
context.textAlign = "left";
context.fontSize = "12px";
context.fillText("Hello World", 0, 0, canvas.width);