version: '3'
services:
  dev-be:
    build:
      context: .
      args:
        MAKE: dev-be
    volumes:
    - ./server:/usr/src/app/server
    - serverBuild:/usr/src/app/serverBuild
  dev-fe:
    build:
      context: .
      args:
        MAKE: dev-fe
    volumes:
    - ./client:/usr/src/app/client
    - clientBuild:/usr/src/app/clientBuild
    ports:
      - "6873:6873"
  dev-forever:
    build:
      context: .
      args:
        MAKE: dev-forever
    volumes:
    - serverBuild:/usr/src/app/serverBuild
    - clientBuild:/usr/src/app/clientBuild
    depends_on:
      - dev-be
      - dev-fe
    ports:
    - "80:80"
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4583:4567-4583"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  serverBuild:
  clientBuild: